### ISSUE TITLE
Don't include node_modules in git

### ISSUE THREAD

**Issue by humphd** [aserputov/qck-ssg-final#1]
In the early days of node, it was common to include node_modules in the git repo.  There are still some people who will tell you to do this.  In general, this practice has been replaced by the combination of the `package.json` file (your specific dependencies defined) and the `package-lock.json` file (your indirect dependencies defined).

We tend to put in git only those files that are required to build the program. Any that can be generated are usually excluded.  Since `npm install` will pull these dependencies into the project automatically, we don't need to include them in the repo.

```
# remove them from future commits
git rm -fr node_modules
# add a .gitignore so they don't get added back again
npx gitignore node
# add this file to git
git add .gitignore
```

**Comment by aserputov** [comment]
Fixed.
