### ISSUE TITLE
Provide useful error messages

### ISSUE THREAD

**Issue by humphd** [aserputov/qck-ssg-final#5]
In a number of cases, you throw errors: https://github.com/aserputov/qck-ssg-final/blob/main/index.js#L111.  This is going to mean that the program crashes and the user is left with a cryptic message and call stack.

Instead, you should log a useful error message.  Useful here means "actionable," and indicates to the user how to fix things so that the program can work next time.  You should also exit the program with an error code (e.g., non-zero error code):

```js
if(err) {
  console.error('Helpful error message here...');
  process.exit(1);
}
```

**Comment by aserputov** [comment]
Done. Thanks.
