### ISSUE TITLE
Support --config with Config File

### ISSUE THREAD

**Issue by abatomunkuev** [aserputov/qck-ssg-final#9]
Hello Anatoliy! 

I would like to work on your project by adding a new feature: support for Configuration Files.

I want users to be able to specify all of their SSG options in a JSON formatted configuration file instead of having to pass them all as command line arguments every time.
```
{ 
   "input": "./site",
   "output": "./build",
   "stylesheet": "https://cdn.jsdelivr.net/npm/water.css@2/out/water.css"
} 
```

**Comment by aserputov** [comment]
no

**Comment by aserputov** [comment]
ponyal

**Comment by aserputov** [comment]
Yes, you can work. Welcome!

**Comment by aserputov** [comment]
I don't like ur work bro

**Comment by aserputov** [comment]
Done! Great Job!
